"""
HTTP client for the review API: TUI and other thin clients call the server over REST.

A session id is generated by default; multi-turn short memory uses the X-Review-Session header.
"""

from __future__ import annotations

import os
import uuid
from pathlib import Path
from typing import Any, Dict, List, Optional

import httpx


def default_api_base() -> str:
    return os.environ.get("REVIEW_AGENT_API_BASE_URL", "http://127.0.0.1:18080").rstrip("/")


class ReviewAPIClient:
    def __init__(
        self,
        base_url: Optional[str] = None,
        session_id: Optional[str] = None,
    ) -> None:
        self.base_url = (base_url or default_api_base()).rstrip("/")
        self.session_id = session_id or str(uuid.uuid4())
        self._session_headers = {"X-Review-Session": self.session_id}

    def new_session(self) -> str:
        """Issue a new session id (callers may DELETE /v1/sessions/{id} to release the old one)."""
        old = self.session_id
        self.session_id = str(uuid.uuid4())
        self._session_headers = {"X-Review-Session": self.session_id}
        return old

    def delete_session_sync(self, session_id: str, timeout: float = 8.0) -> None:
        try:
            httpx.delete(
                f"{self.base_url}/v1/sessions/{session_id}",
                timeout=timeout,
            )
        except httpx.HTTPError:
            pass

    def health_sync(self, timeout: float = 3.0) -> bool:
        try:
            r = httpx.get(f"{self.base_url}/health", timeout=timeout)
            return r.status_code == 200
        except httpx.HTTPError:
            return False

    async def health(self, timeout: float = 5.0) -> bool:
        try:
            async with httpx.AsyncClient(timeout=timeout) as client:
                r = await client.get(f"{self.base_url}/health")
                return r.status_code == 200
        except httpx.HTTPError:
            return False

    async def moderate(self, content: str, content_type: str = "auto") -> Dict[str, Any]:
        async with httpx.AsyncClient(timeout=600.0) as client:
            r = await client.post(
                f"{self.base_url}/v1/review",
                json={"content": content, "content_type": content_type},
                headers=self._session_headers,
            )
            self._raise_for_status(r)
            return r.json()

    async def moderate_file(self, path: Path) -> Dict[str, Any]:
        import mimetypes

        p = Path(path).expanduser().resolve()
        mime, _ = mimetypes.guess_type(str(p))
        mime = mime or "application/octet-stream"
        data = p.read_bytes()
        async with httpx.AsyncClient(timeout=600.0) as client:
            r = await client.post(
                f"{self.base_url}/v1/review/file",
                files={"file": (p.name, data, mime)},
                headers=self._session_headers,
            )
            self._raise_for_status(r)
            return r.json()

    async def moderate_files(self, paths: List[Path]) -> Dict[str, Any]:
        """Multiple files in one request (multipart with repeated ``files`` parts)."""
        import mimetypes

        plist = [Path(p).expanduser().resolve() for p in paths]
        if len(plist) == 1:
            return await self.moderate_file(plist[0])

        parts: List[tuple[str, tuple[str, bytes, str]]] = []
        for p in plist:
            mime, _ = mimetypes.guess_type(str(p))
            mime = mime or "application/octet-stream"
            parts.append(("files", (p.name, p.read_bytes(), mime)))

        async with httpx.AsyncClient(timeout=1200.0) as client:
            r = await client.post(
                f"{self.base_url}/v1/review/file",
                files=parts,
                headers=self._session_headers,
            )
            self._raise_for_status(r)
            return r.json()

    def list_tool_packs_sync(self, timeout: float = 5.0) -> Optional[Dict[str, Any]]:
        """GET /v1/tool-packs."""
        try:
            r = httpx.get(f"{self.base_url}/v1/tool-packs", timeout=timeout)
            if r.status_code == 200:
                return r.json()
        except httpx.HTTPError:
            return None
        return None

    def get_llm_config_sync(self, timeout: float = 8.0) -> Optional[Dict[str, Any]]:
        """GET /v1/config/llm."""
        try:
            r = httpx.get(f"{self.base_url}/v1/config/llm", timeout=timeout)
            if r.status_code == 200:
                return r.json()
        except httpx.HTTPError:
            return None
        return None

    def patch_llm_config_sync(
        self, body: Dict[str, Any], timeout: float = 15.0
    ) -> Dict[str, Any]:
        """PATCH /v1/config/llm; raises RuntimeError on failure (same as moderate)."""
        r = httpx.patch(
            f"{self.base_url}/v1/config/llm",
            json=body,
            timeout=timeout,
        )
        self._raise_for_status(r)
        return r.json()

    def get_display_config_sync(self, timeout: float = 8.0) -> Optional[Dict[str, Any]]:
        """GET /v1/config/display (report language, etc.)."""
        try:
            r = httpx.get(f"{self.base_url}/v1/config/display", timeout=timeout)
            if r.status_code == 200:
                return r.json()
        except httpx.HTTPError:
            return None
        return None

    def patch_display_config_sync(
        self, body: Dict[str, Any], timeout: float = 15.0
    ) -> Dict[str, Any]:
        """PATCH /v1/config/display."""
        r = httpx.patch(
            f"{self.base_url}/v1/config/display",
            json=body,
            timeout=timeout,
        )
        self._raise_for_status(r)
        return r.json()

    @staticmethod
    def _raise_for_status(r: httpx.Response) -> None:
        try:
            r.raise_for_status()
        except httpx.HTTPStatusError as e:
            body = (e.response.text or "")[:800]
            raise RuntimeError(f"HTTP {e.response.status_code}: {body or e.response.reason_phrase}") from e


__all__ = ["ReviewAPIClient", "default_api_base"]
